# Generated by Django 5.2.7 on 2025-10-14 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito_judicial', models.CharField(max_length=100)),
                ('numero_expediente', models.CharField(max_length=50)),
                ('parte', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('acto_procesal', models.CharField(max_length=200)),
                ('resolucion', models.CharField(max_length=200)),
                ('sumilla', models.CharField(max_length=500)),
                ('archivo_pdf', models.FileField(upload_to='expedientes/pdfs/')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expedientes.expediente')),
            ],
        ),
    ]
