# Generated by Django 5.2.7 on 2025-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo_pdf',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
